import express from "express";
import { handleError } from "../utils/error.util.ts";

export const getBids = async (req: express.Request, res: express.Response) => {
  console.log(req.user);
  try {
    const bids = [
      {
        id: "bid_001",
        property_id: "prop_123",
        property_title: "Luxury Downtown Apartment",
        bidder_id: "user_456",
        bidder_name: "John Smith",
        bidder_avatar: "https://example.com/avatars/john.jpg",
        amount: 250000.0,
        bid_type: "live",
        status: "winning",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-15T14:30:25Z",
        updated_at: "2024-01-15T14:30:25Z",
      },
      {
        id: "bid_002",
        property_id: "prop_123",
        property_title: "Luxury Downtown Apartment",
        bidder_id: "user_789",
        bidder_name: "Sarah Johnson",
        bidder_avatar: "https://example.com/avatars/sarah.jpg",
        amount: 245000.0,
        bid_type: "live",
        status: "outbid",
        is_auto_bid: true,
        max_auto_bid: 260000.0,
        created_at: "2024-01-15T14:28:10Z",
        updated_at: "2024-01-15T14:30:25Z",
      },
      {
        id: "bid_003",
        property_id: "prop_123",
        property_title: "Luxury Downtown Apartment",
        bidder_id: "user_456",
        bidder_name: "John Smith",
        bidder_avatar: "https://example.com/avatars/john.jpg",
        amount: 240000.0,
        bid_type: "live",
        status: "outbid",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-15T14:25:45Z",
        updated_at: "2024-01-15T14:28:10Z",
      },
      {
        id: "bid_004",
        property_id: "prop_456",
        property_title: "Vintage Sports Car",
        bidder_id: "user_101",
        bidder_name: "Mike Wilson",
        bidder_avatar: "https://example.com/avatars/mike.jpg",
        amount: 35000.0,
        bid_type: "sealed",
        status: "active",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-15T13:15:30Z",
        updated_at: "2024-01-15T13:15:30Z",
      },
      {
        id: "bid_005",
        property_id: "prop_456",
        property_title: "Vintage Sports Car",
        bidder_id: "user_202",
        bidder_name: "Emily Chen",
        bidder_avatar: "https://example.com/avatars/emily.jpg",
        amount: 38000.0,
        bid_type: "sealed",
        status: "active",
        is_auto_bid: true,
        max_auto_bid: 42000.0,
        created_at: "2024-01-15T13:20:15Z",
        updated_at: "2024-01-15T13:20:15Z",
      },
      {
        id: "bid_006",
        property_id: "prop_789",
        property_title: "Commercial Office Space",
        bidder_id: "user_303",
        bidder_name: "David Brown",
        bidder_avatar: "https://example.com/avatars/david.jpg",
        amount: 750000.0,
        bid_type: "fixed",
        status: "won",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-14T10:00:00Z",
        updated_at: "2024-01-14T15:00:00Z",
      },
      {
        id: "bid_007",
        property_id: "prop_101",
        property_title: "Rare Electronics Collection",
        bidder_id: "user_404",
        bidder_name: "Lisa Rodriguez",
        bidder_avatar: "https://example.com/avatars/lisa.jpg",
        amount: 1200.0,
        bid_type: "live",
        status: "winning",
        is_auto_bid: true,
        max_auto_bid: 1500.0,
        created_at: "2024-01-15T15:45:20Z",
        updated_at: "2024-01-15T15:45:20Z",
      },
      {
        id: "bid_008",
        property_id: "prop_101",
        property_title: "Rare Electronics Collection",
        bidder_id: "user_505",
        bidder_name: "Alex Kim",
        bidder_avatar: "https://example.com/avatars/alex.jpg",
        amount: 1100.0,
        bid_type: "live",
        status: "outbid",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-15T15:40:10Z",
        updated_at: "2024-01-15T15:45:20Z",
      },
      {
        id: "bid_009",
        property_id: "prop_202",
        property_title: "Beachfront Property",
        bidder_id: "user_606",
        bidder_name: "Robert Taylor",
        bidder_avatar: "https://example.com/avatars/robert.jpg",
        amount: 1200000.0,
        bid_type: "sealed",
        status: "active",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-15T09:30:00Z",
        updated_at: "2024-01-15T09:30:00Z",
      },
      {
        id: "bid_010",
        property_id: "prop_202",
        property_title: "Beachfront Property",
        bidder_id: "user_707",
        bidder_name: "Maria Garcia",
        bidder_avatar: "https://example.com/avatars/maria.jpg",
        amount: 1250000.0,
        bid_type: "sealed",
        status: "active",
        is_auto_bid: true,
        max_auto_bid: 1400000.0,
        created_at: "2024-01-15T10:15:30Z",
        updated_at: "2024-01-15T10:15:30Z",
      },
      {
        id: "bid_011",
        property_id: "prop_303",
        property_title: "Antique Furniture Set",
        bidder_id: "user_808",
        bidder_name: "James Wilson",
        bidder_avatar: "https://example.com/avatars/james.jpg",
        amount: 4500.0,
        bid_type: "live",
        status: "lost",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-13T14:20:00Z",
        updated_at: "2024-01-13T16:00:00Z",
      },
      {
        id: "bid_012",
        property_id: "prop_303",
        property_title: "Antique Furniture Set",
        bidder_id: "user_909",
        bidder_name: "Jennifer Lee",
        bidder_avatar: "https://example.com/avatars/jennifer.jpg",
        amount: 4800.0,
        bid_type: "live",
        status: "won",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-13T15:55:30Z",
        updated_at: "2024-01-13T16:00:00Z",
      },
      {
        id: "bid_013",
        property_id: "prop_404",
        property_title: "Mountain Land Plot",
        bidder_id: "user_1010",
        bidder_name: "Thomas Moore",
        bidder_avatar: "https://example.com/avatars/thomas.jpg",
        amount: 85000.0,
        bid_type: "fixed",
        status: "active",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-15T16:20:45Z",
        updated_at: "2024-01-15T16:20:45Z",
      },
      {
        id: "bid_014",
        property_id: "prop_505",
        property_title: "Designer Handbag Collection",
        bidder_id: "user_1111",
        bidder_name: "Amanda Clark",
        bidder_avatar: "https://example.com/avatars/amanda.jpg",
        amount: 3200.0,
        bid_type: "live",
        status: "winning",
        is_auto_bid: true,
        max_auto_bid: 4000.0,
        created_at: "2024-01-15T17:10:30Z",
        updated_at: "2024-01-15T17:10:30Z",
      },
      {
        id: "bid_015",
        property_id: "prop_505",
        property_title: "Designer Handbag Collection",
        bidder_id: "user_1212",
        bidder_name: "Christopher Hall",
        bidder_avatar: "https://example.com/avatars/chris.jpg",
        amount: 3000.0,
        bid_type: "live",
        status: "outbid",
        is_auto_bid: false,
        max_auto_bid: null,
        created_at: "2024-01-15T17:05:15Z",
        updated_at: "2024-01-15T17:10:30Z",
      },
    ];
    res.status(200).json(bids);
  } catch (error) {
    handleError(res, error);
  }
};
